version: '3.8'

services:
  ml_app:
    build: .
    container_name: ml_application
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./data:/app/data
      - ./models:/app/models
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  data:
  models:
